state_code_dict = tribble(
  # Source: https://www.cms.gov/Medicare/Provider-Enrollment-and-Certification/SurveyCertificationGenInfo/Downloads/Survey-and-Cert-Letter-16-09.pdf
  # Dropped non-states, per analysis
  ~state_name,~SP_STATE_CODE,
  'Alabama','01',
  'New Hampshire','30',
  'Alaska','02',
  'New Jersey','31',
  'New Jersey','83',
  'Arizona','03',
  'New Mexico','32',
  'New Mexico','96',
  'Arkansas','04',
  'Arkansas','89',
  'New York','33',
  'California','05',
  'California','55',
  'California','75',
  'California','92',
  'North Carolina','34',
  'North Carolina','86',
  'Colorado','06',
  'Colorado','91',
  'North Dakota','35',
  'Connecticut','07',
  'Connecticut','81',
  'Ohio','36',
  'Ohio','72',
  'Delaware','08',
  'Oklahoma','37',
  'Oklahoma','90',
  #'District of Columbia','09',
  'Oregon','38',
  'Oregon','93',
  'Florida','10',
  'Florida','68',
  'Florida','69',
  'Pennsylvania','39',
  'Pennsylvania','73',
  'Georgia','11',
  'Georgia','85',
  #'Puerto Rico','40',
  #'Puerto Rico','84',
  'Hawaii','12',
  'Rhode Island','41',
  'Idaho','13',
  'South Carolina','42',
  'South Carolina','87',
  'Illinois','14',
  'Illinois','78',
  'South Dakota','43',
  'Indiana','15',
  'Tennessee','44',
  'Tennessee','88',
  'Iowa','16',
  'Iowa','76',
  'Texas','45',
  'Texas','67',
  'Texas','74',
  'Texas','97',
  'Kansas','17',
  'Kansas','70',
  'Utah','46',
  'Kentucky','18',
  'Vermont','47',
  'Louisiana','19',
  'Louisiana','71',
  'Louisiana','95',
  #'Virgin Islands','48',
  'Maine','20',
  'Virginia','49',
  'Maryland','21',
  'Maryland','80',
  'Washington','50',
  'Washington','94',
  'Massachusetts','22',
  'Massachusetts','82',
  'West Virginia','51',
  'Michigan','23',
  'Wisconsin','52',
  'Minnesota','24',
  'Minnesota','77',
  'Wyoming','53',
  'Mississippi','25',
  #'Canada','56',
  'Missouri','26',
  'Missouri','79',
  #'Mexico','59',
  'Montana','27',
  #'American Samoa','64',
  'Nebraska','28',
  #'Guam','65',
  'Nevada','29',
  #'Commonwealth of the Northern Marianas Islands','66',
  #'Foreign Countries','99'
)
